# GitHub 赞助配置
# 如果你想接受赞助，可以取消注释并填写相应信息

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-open-collective
# ko_fi: your-ko-fi-username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# lfx_crowdfunding: project-name
# custom: ['https://your-website.com', 'https://another-site.com']
